// src/App/components/ChartTable/ChartTableRow.tsx
import React from "react";
import { TableCell, TableRow } from "@mui/material";
import { Chart } from "@/Domain/Chart";
import { formatNum, roundFormat } from "@/App/utils/format";

type Props = {
  item: Chart
}

export const ChartTableRow: React.FC<Props> = ({ item }) => {
	return (
		<>
			{
				item.year
					? (<TableRow>
						<TableCell colSpan={ Object.keys(item).length }>
							{ item.year }
						</TableCell>
					</TableRow>)
					: null
			}
			<TableRow
				sx={ { "&:last-child td, &:last-child th": { border: 0 } } }
			>
				<TableCell>{ item.month }</TableCell>
				<TableCell>{ roundFormat(item.annuitet) } ₽</TableCell>
				<TableCell>{ formatNum(item.rateSum) } ₽</TableCell>
				<TableCell>{ formatNum(item.loanSum) } ₽</TableCell>
				<TableCell>{ formatNum(item.leftToPay) } ₽</TableCell>
			</TableRow>
		</>
	);
};

// src/App/components/ChartTableRow.vue
<template>
  <tr>
    <td class="text-h6 font-weight-regular">{{ item.month }}</td>
    <td class="text-h6 font-weight-regular text-right">{{ item.annuitet|roundFormat }} ₽</td>
    <td class="text-h6 font-weight-regular grey--text text-right">{{ item.rateSum|formatNum }} ₽</td>
    <td class="text-h6 font-weight-regular grey--text text-right">{{ item.loanSum|formatNum }} ₽</td>
    <td class="text-h6 font-weight-regular text-right">{{ item.leftToPay|formatNum }} ₽</td>
  </tr>
</template>

<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  name: 'ChartTableRow',
  props: ['item']
})
</script>
