// src/App/components/InputGroup.tsx
import "reflect-metadata";
import React, { useContext, useEffect } from 'react';
import { Box, Grid } from '@material-ui/core';
import { SelectItemInput } from '@/App/components/inputs/SelectItemInput';
import { CalculatorDI, ICalculatorUseCase } from "@/Domain/CalculatorUseCase";
import { AppContext } from "@/App/HOC/Provider";
import { StoreDI, Store } from "@/Store/Store";
import { useQuery } from "@apollo/client";
import { GET_LOAN_REASONS } from "@/Store/QueryGQL";
import { interfaces } from "inversify";
import { Calculator } from "@/Domain/Calculator";
import { CalcStoreProvider } from "@/App/store/CalcStoreProvider";
import { SliderInput } from "@/App/components/inputs/SliderInput";

export const InputGroup: React.FC = () => {
  const container = useContext<interfaces.Container>(AppContext);
  const Store = container.get<Store>(StoreDI);
  const queries = Store.queries;
  const { loading, error, data } = useQuery(queries.GET_LOAN_REASONS);



  // setTimeout(() => {
  //   update({ houseCost: { value: 1 } });
  // }, 100);

  return (
    <Grid xs={ 6 } item>
      <Box p={ 2 }>
        <form>
          <SelectItemInput />
          <SliderInput />
        </form>
      </Box>
    </Grid>
  );
};

// src/App/components/InputGroup.vue
<template>
  <v-col class="col-6" :align-self="'start'">
    <v-row>
      <v-col class="col-12">
        <SelectListUI
            :data="loanReasonsListData"
            :label="'Цель кредита'"
            :hasBorder="true"
        />
      </v-col>
      <v-spacer />
      <v-col class="col-12">
        <SwitchInputUI :label="'Есть зарплатная карта'" />
      </v-col>
      <v-col class="col-12">
        <SliderInputUI :label="'Стоимость недвижимости'"/>
      </v-col>
      <v-col class="col-12">
        <SliderInputUI :label="'Первоначальный взнос'"/>
      </v-col>
      <v-col class="col-12">
        <SliderInputUI :label="'Срок Кредита'"/>
      </v-col>
    </v-row>
  </v-col>
</template>

<script lang="ts">
import 'reflect-metadata'
import Vue from 'vue'
import Component from 'vue-class-component'
import { Container } from 'inversify'
import { Inject } from 'vue-property-decorator'
import InputLayout from '@/App/UI/BaseInput.vue'
import SelectListUI from '@/App/UI/SelectListInputUI.vue'
import SwitchInputUI from '@/App/UI/SwitchInputUI.vue'
import SliderInputUI from '@/App/UI/SliderInputUI.vue'
import { DocumentNode } from 'graphql'
import { IStore, StoreDI } from '@/Store/Store'
import { ICalculatorUseCase, CalculatorDI } from '@/Domain/CalculatorUseCase'
import { LoanReasonList } from '@/Domain/LoanReasonList'

@Component({
  components: { InputLayout, SelectListUI, SwitchInputUI, SliderInputUI },
  apollo: {
    loanReasonsList: {
      query () { return this.queries.GET_LOAN_REASONS },
      update ({ loanReasonsList }): LoanReasonList {
        this.calculator.loanReasonList = loanReasonsList
        this.loanReasonsListData = this.calculator.loanReasonList
      },
    },
  }
})
export default class InputGroup extends Vue {
  @Inject('container') private readonly containerDI!: Container
  private readonly store: IStore = this.containerDI.get(StoreDI)
  private readonly queries: { [key: string]: DocumentNode } = this.store.queries
  private readonly calculator: ICalculatorUseCase = this.containerDI.get(CalculatorDI)

  private readonly loanReasonsListData: LoanReasonList = this.calculator.loanReasonList

}
</script>
