// src/App/App.tsx
import React, { useContext } from 'react';
import { ICalculatorUseCase } from '@/Domain/CalculatorUseCase';
import { Context } from '@/App/HOC/StoreProvider';
import { FormLayout } from '@/App/HOC/FormLayout';
import {InputGroup} from "@/App/components/InputGroup";
import {Total} from "@/App/components/Total";

const App: React.FC = () => {
  return (
    <FormLayout>
      <InputGroup  />
      <Total />
    </FormLayout>
  );
};

export default App;

// src/app/App.vue
<template>
  <v-app>
    <v-main>
      <Layout>
        <InputGroup/>
        <Total/>
      </Layout>
    </v-main>
  </v-app>
</template>

<script lang="ts">
  import Vue from 'vue'
  import Layout from "@/App/components/Layout.vue";
  import Component from 'vue-class-component'
  import Total from "@/App/components/Total.vue";
  import InputGroup from "@/App/components/InputGroup.vue";

  @Component({components: {Layout, Total, InputGroup}})
  export default class App extends Vue {}
</script>
